version: '2.4'

services:
  rabbitmq:
    hostname: 'rabbit'
    image: rabbitmq:3.10-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 10s
      retries: 3
    environment:
      SERVER_PORT: 8080
    ports:
      - '5672:5672'
      - '15672:15672'

  message-analyzer:
    image: application/message-analyzer:simple
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 3
    environment:
      SERVER_PORT: 8080
    ports:
      - 8092:8080

  medical-monitoring:
    image: application/medical-monitoring:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 3
    environment:
      SERVER_PORT: 8080
    ports:
      - 8093:8080

  person-service:
    image: application/person-service:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
      medical-monitoring:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 3
    environment:
        SERVER_PORT: 8080
    ports:
        - 8091:8080